# Generated by Django 3.0.4 on 2020-04-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyBills',
            new_name='MonthlyBill',
        ),
    ]
