# Generated by Django 3.0.4 on 2020-04-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0002_auto_20200405_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='auto_pay_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
